name: Deploy Dev
on:
  push:
    branches:
      - dev
jobs:
  deploy-dev:
    container: public.ecr.aws/sam/build-python3.9:latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
    steps:
      - name: SAM Build
        run: sam build
      - name: SAM Deploy
        run: sam deploy --stack-name starfinder-discord-bot-dev
