name: Deploy Dev
on:
  push:
    branches:
      - dev
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: aws-actions/setup-sam@v1
      - name: SAM Build
        run: sam build --use-container
      - name: SAM Deploy
        run: sam deploy --stack-name starfinder-discord-bot-dev
