name: Deploy Dev
on:
  push:
    branches:
      - dev
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: List dir
        run: ls
      - name: Change Directory into src
        run: cd ./src
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
      - name: Install NPM dependencies
        run: npm install
      - name: Deploy Lambda functions
        run: sls deploy -s dev
